### ISSUE TITLE
Uncaught TypeError: Cannot read property 'toString' of null

### ISSUE THREAD

**Issue by denegny** [tombell/travis-ci-status#33]
Uncaught TypeError: Cannot read property 'toString' of null

**Atom Version**: 0.158.0
**System**: linux 3.13.0-37-generic
**Thrown From**: [travis-ci-status](https://github.com/tombell/travis-ci-status) package, v0.11.0

### Steps To Reproduce

1. ...
2. ...

### Stack Trace

```
At /home/jarto/.atom/packages/travis-ci-status/lib/build-matrix-view.coffee:71

TypeError: Cannot read property 'toString' of null
  at BuildMatrixView.module.exports.BuildMatrixView.buildMatrix (/home/jarto/.atom/packages/travis-ci-status/lib/build-matrix-view.coffee:71:41)
  at /home/jarto/.atom/packages/travis-ci-status/lib/build-matrix-view.coffee:1:1
  at Request._callback (/home/jarto/.atom/packages/travis-ci-status/node_modules/travis-ci/lib/travis-http.js:36:13)
  at Request.self.callback (/home/jarto/.atom/packages/travis-ci-status/node_modules/travis-ci/node_modules/request/index.js:148:22)
  at Request.emit (events.js:110:17)
  at Request.<anonymous> (/home/jarto/.atom/packages/travis-ci-status/node_modules/travis-ci/node_modules/request/index.js:886:14)
  at Request.emit (events.js:129:20)
  at IncomingMessage.<anonymous> (/home/jarto/.atom/packages/travis-ci-status/node_modules/travis-ci/node_modules/request/index.js:837:12)
  at IncomingMessage.emit (events.js:129:20)
  at _stream_readable.js:907:16
  at process._tickCallback (node.js:378:11)

```

/cc @atom/core

**Comment by magalhas** [comment]
@pariser I'm afraid I don't have a Travis CI Pro account in order to reproduce and fix this bug.

**Comment by avdg** [comment]
It would be nice to know what the parameters of https://github.com/tombell/travis-ci-status/blob/master/lib/build-matrix-view.coffee#L67 could be

**Comment by magalhas** [comment]
Are you still experiencing this ?

**Comment by pariser** [comment]
Hey @magalhas I haven't seen this issue pop up in a while. I'll be sure to chime in if I see it again. I wish I knew exactly what I was doing to trigger the bug so I could try to reproduce it.

**Comment by magalhas** [comment]
Thank you. I'm going to close this issue then.
