### ISSUE TITLE
Package activation fails after upgrading to Atom 0.172.0

### ISSUE THREAD

**Issue by olmokramer** [tombell/travis-ci-status#36]
Package activation fails after upgrading to Atom 0.172.0. Activation enters an infinite loop:

```
Failed to activate package named 'travis-ci-status' RangeError: Maximum call stack size exceeded
at require.deprecate (/usr/share/atom/resources/app/src/atom.js:null:null)
at GitRepository.module.exports.GitRepository.getOriginUrl (/usr/share/atom/resources/app/src/git-repository.js:198:7)
at GitRepository.module.exports.GitRepository.getOriginUrl (/usr/share/atom/resources/app/src/git-repository.js:199:19)
```
(insert last line a few thousand times)
```
at GitRepository.module.exports.GitRepository.getOriginUrl (/usr/share/atom/resources/app/src/git-repository.js:199:19)
at Object.module.exports.isGitHubRepo (/home/olmo/.atom/packages/travis-ci-status/lib/travis-ci-status.coffee:50:34)
at Object.module.exports.activate (/home/olmo/.atom/packages/travis-ci-status/lib/travis-ci-status.coffee:29:6)
at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app/src/package.js:235:27)
at /usr/share/atom/resources/app/src/package.js:221:28
at Package.module.exports.Package.measure (/usr/share/atom/resources/app/src/package.js:167:15)
at Package.module.exports.Package.activate (/usr/share/atom/resources/app/src/package.js:215:14)
at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app/src/package-manager.js:453:21)
at /usr/share/atom/resources/app/src/package-manager.js:434:29
at Config.module.exports.Config.transact (/usr/share/atom/resources/app/src/config.js:344:16)
at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom/resources/app/src/package-manager.js:428:19)
at PackageManager.module.exports.PackageManager.activate (/usr/share/atom/resources/app/src/package-manager.js:411:46)
at Atom.module.exports.Atom.startEditorWindow (/usr/share/atom/resources/app/src/atom.js:605:21)
at Object.<anonymous> (/usr/share/atom/resources/app/src/window-bootstrap.js:12:8)
at Object.<anonymous> (/usr/share/atom/resources/app/src/window-bootstrap.js:23:4)
at Module._compile (module.js:468:26)
at Object.Module._extensions..js (module.js:486:10)
at Module.load (/usr/share/atom/resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
at Function.Module._load (module.js:318:12)
at Module.require (module.js:373:17)
at require (module.js:392:17)
at window.onload (file:///usr/share/atom/resources/app/static/index.js:66:25)
```

## Repro Steps

1. Start Atom v0.172.0 with this package enabled

**Expected:** Package activates

**Actual:** Package enters an infinite loop and doesn't activate

## Versions

* **Atom:**       0.172.0
* **Atom-Shell:** 0.20.5
* **OS:**         linux 3.18-2.dmz.1-liquorix-amd64
* **Misc**
    * apm  0.119.0
    * npm  1.4.4
    * node 0.10.35
    * python 2.7.8
    * git 2.1.4

---

<small>This report was created in and posted from the Atom editor using the package `bug-report` v0.5.3.</small>

**Comment by magalhas** [comment]
I'll take a look into this ASAP

**Comment by magalhas** [comment]
Do you still experience this?

**Comment by olmokramer** [comment]
Nope, seems to be gone :)
