### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by stain** [tombell/travis-ci-status#40]
Uncaught TypeError: undefined is not a function

**Atom Version**: 0.155.0
**System**: linux 3.16.0-30-generic
**Thrown From**: [travis-ci-status](https://github.com/tombell/travis-ci-status) package, v0.11.2

### Steps To Reproduce

1. git clone https://github.com/openphacts/ops.js
2. cd ops.js
2. atom .

### Stack Trace

```
At /home/stain/.atom/packages/travis-ci-status/lib/build-status-view.coffee:37

TypeError: undefined is not a function
  at BuildStatusView.module.exports.BuildStatusView.attach (/home/stain/.atom/packages/travis-ci-status/lib/build-status-view.coffee:37:36)
  at BuildStatusView.module.exports.BuildStatusView.initialize (/home/stain/.atom/packages/travis-ci-status/lib/build-status-view.coffee:23:6)
  at BuildStatusView.View (/home/stain/.atom/packages/travis-ci-status/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
  at new BuildStatusView (/home/stain/.atom/packages/travis-ci-status/lib/build-status-view.coffee:9:3)
  at /home/stain/.atom/packages/travis-ci-status/lib/travis-ci-status.coffee:90:30
  at Object.module.exports.init (/home/stain/.atom/packages/travis-ci-status/lib/travis-ci-status.coffee:94:7)
  at /home/stain/.atom/packages/travis-ci-status/lib/travis-ci-status.coffee:33:56
  at Object.cb [as oncomplete] (fs.js:187:19)

```

## travis.yml

```
stain@biggie-utopic:~/src/ops.js$ cat .travis.yml 
branches:
  only:
    - develop
script:
  - "phantomjs --local-to-remote-url-access=yes --ignore-ssl-errors=yes test/spec/phantomjs_jasminexml_runner.js test/PhantomIntegrationTests.html 1c22cbe7 167a3a3d8539b5d85280e7178f4e62ab https://beta.openphacts.org/1.4 testout"
```

https://travis-ci.org/openphacts/ops.js

/cc @atom/core

**Comment by magalhas** [comment]
Hi, are you using a pro account or a free one?

**Comment by stain** [comment]
Free account. This happened also now with https://github.com/jai-imageio/jai-imageio-core
```
stain@biggie-utopic:~/src/jai-imageio-core$ cat .travis.yml 
language: java
jdk:
  - oraclejdk7
  - oraclejdk8
  - openjdk6
  - openjdk7
```
https://travis-ci.org/jai-imageio/jai-imageio-core
