### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getOriginURL' of null

### ISSUE THREAD

**Issue by razmo** [tombell/travis-ci-status#57]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.198.0
**System**: Mac OS X 10.10.3
**Thrown From**: [travis-ci-status](https://github.com/tombell/travis-ci-status) package, v0.14.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getOriginURL' of null

```
At /Users/jamal/.atom/packages/travis-ci-status/lib/build-status-view.coffee:71

TypeError: Cannot read property 'getOriginURL' of null
  at /Users/jamal/.atom/packages/travis-ci-status/lib/build-status-view.coffee:71:57
  at Array.filter (native)
  at BuildStatusView.module.exports.BuildStatusView.subscribeToRepo (/Users/jamal/.atom/packages/travis-ci-status/lib/build-status-view.coffee:71:18)
  at BuildStatusView.subscribeToRepo (/Users/jamal/.atom/packages/travis-ci-status/lib/build-status-view.coffee:1:1)
  at BuildStatusView.module.exports.BuildStatusView.initialize (/Users/jamal/.atom/packages/travis-ci-status/lib/build-status-view.coffee:21:6)
  at BuildStatusView.View (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
  at new BuildStatusView (/Users/jamal/.atom/packages/travis-ci-status/lib/build-status-view.coffee:9:3)
  at /Users/jamal/.atom/packages/travis-ci-status/lib/travis-ci-status.coffee:106:30
  at Object.module.exports.init (/Users/jamal/.atom/packages/travis-ci-status/lib/travis-ci-status.coffee:111:7)
  at /Users/jamal/.atom/packages/travis-ci-status/lib/travis-ci-status.coffee:38:48
  at FSReqWrap.cb [as oncomplete] (fs.js:209:19)

```

### Commands

```
 15x -2:19.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:51 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:35.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:32.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "projectHome": "/Users/jamal/Developments"
  }
}
```

### Installed Packages

```coffee
# User
atom-phpcs, v0.7.0
autocomplete-php, v0.3.4
color-picker, v1.7.0
php-getters-setters, v0.3.0
php-twig, v3.0.0
symfony-snippets, v0.3.0
trailing-spaces, v0.2.5
travis-ci-status, v0.14.0

# Dev
No dev packages
```

**Comment by tombell** [comment]
Just pushed `v0.14.1`, which `console.log`'s the value of `repos`, if you could open the same project, then copy and paste what is outputted by the `console.log`.

**Comment by razmo** [comment]
Thank you for you fast answer. 
I removed and then reinstall the package and there are no more errors.

**Comment by tombell** [comment]
Interesting, okay.

I’ll close the issue, if you encounter it again, feel free to reopen this issue.  

— Tom
