### ISSUE TITLE
Uncaught TypeError: Cannot read property 'split' of null

### ISSUE THREAD

**Issue by mwksl** [tombell/travis-ci-status#65]
1. Install travis-ci-status through apm command while atom is open.
2. Quit atom and reopen.

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: [travis-ci-status](https://github.com/tombell/travis-ci-status) package, v0.15.1

### Stack Trace

Uncaught TypeError: Cannot read property 'split' of null

```
At /Users/mwksl/.atom/packages/travis-ci-status/lib/build-status-view.coffee:89

TypeError: Cannot read property 'split' of null
  at BuildStatusView.module.exports.BuildStatusView.update (/Users/mwksl/.atom/packages/travis-ci-status/lib/build-status-view.coffee:89:19)
  at BuildStatusView.update (/Users/mwksl/.atom/packages/travis-ci-status/lib/build-status-view.coffee:1:1)
  at BuildStatusView.module.exports.BuildStatusView.subscribeToRepo (/Users/mwksl/.atom/packages/travis-ci-status/lib/build-status-view.coffee:80:6)
  at BuildStatusView.subscribeToRepo (/Users/mwksl/.atom/packages/travis-ci-status/lib/build-status-view.coffee:1:1)
  at BuildStatusView.module.exports.BuildStatusView.initialize (/Users/mwksl/.atom/packages/travis-ci-status/lib/build-status-view.coffee:21:6)
  at BuildStatusView.View (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
  at new BuildStatusView (/Users/mwksl/.atom/packages/travis-ci-status/lib/build-status-view.coffee:9:3)
  at /Users/mwksl/.atom/packages/travis-ci-status/lib/travis-ci-status.coffee:110:30
  at Object.module.exports.init (/Users/mwksl/.atom/packages/travis-ci-status/lib/travis-ci-status.coffee:115:7)
  at /Users/mwksl/.atom/packages/travis-ci-status/lib/travis-ci-status.coffee:38:48

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
linter, v1.1.0
minimap, v4.10.1
travis-ci-status, v0.15.1

# Dev
No dev packages
```

**Comment by tombell** [comment]
Could not reproduce this on the latest Atom.

**Comment by devurandom** [comment]
This happens on Atom 1.3.2 with Travis-CI-Status 0.18.0. I see the orange clock icon and the message "No build matrix fetched".

[Enter steps to reproduce below:]

1. Edit file in editor
2. Save file
3. Observe exception message

**Atom Version**: 1.3.2
**System**: Ubuntu 14.04.3
**Thrown From**: [travis-ci-status](https://github.com/tombell/travis-ci-status) package, v0.18.0


### Stack Trace

Uncaught TypeError: Cannot read property 'split' of null

```
At /usr/share/atom/resources/app.asar/src/pane.js:829

TypeError: Cannot read property 'split' of null
  at BuildStatusView.module.exports.BuildStatusView.update ($HOME/.atom/packages/travis-ci-status/lib/build-status-view.coffee:94:19)
  at $HOME/.atom/packages/travis-ci-status/lib/build-status-view.coffee:1:1
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
  at GitRepository.module.exports.GitRepository.getPathStatus (/usr/share/atom/resources/app.asar/src/git-repository.js:256:22)
  at /usr/share/atom/resources/app.asar/src/git-repository.js:326:26
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
  at TextBuffer.module.exports.TextBuffer.saveAs (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1060:27)
  at TextBuffer.module.exports.TextBuffer.save (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1030:19)
  at TextEditor.module.exports.TextEditor.save (/usr/share/atom/resources/app.asar/src/text-editor.js:588:26)
  at Pane.module.exports.Pane.saveItem (/usr/share/atom/resources/app.asar/src/pane.js:534:18)
  at Pane.module.exports.Pane.saveActiveItem (/usr/share/atom/resources/app.asar/src/pane.js:517:19)
  at Workspace.module.exports.Workspace.saveActivePaneItem (/usr/share/atom/resources/app.asar/src/workspace.js:633:35)
  at atom-workspace.commandRegistry.add.core:save (/usr/share/atom/resources/app.asar/src/register-default-commands.js:173:32)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
  at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:97:36)
  at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)

```

### Commands

```
     -7:10.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -7:02.8.0 command-palette:toggle (div.package-detail.panels-item)
     -7:00.4.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -7:00.4.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -6:53.4.0 command-palette:toggle (button.btn.icon.icon-trashcan.uninstall-button)
  5x -6:50.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -6:48.8.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -6:48.7.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -5:27.6.0 core:close (button.btn.icon.icon-trashcan.uninstall-button)
     -5:08.3.0 nuclide-health:open-pane (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -5:04.7.0 core:close (atom-pane.pane.active)
     -1:44.5.0 core:backspace (span.build-status.icon.icon-history.pending)
     -1:41.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:40.8.0 core:save (atom-text-editor.editor.is-focused)
     -1:38.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:38.1.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "linter",
      "tree-view"
    ]
  },
  "travis-ci-status": {}
}
```

### Installed Packages

```coffee
# User
Parinfer, v1.5.0
hyperclick, v0.0.35
language-cuda, v0.1.0
language-glsl, v2.0.1
language-hlsl, v1.2.0
language-hy, v0.1.0
language-latex, v0.6.1
language-lua, v0.9.4
language-opencl, v0.1.1
language-rust, v0.4.5
language-tmux, v0.4.0
latex, v0.28.2
latexer, v0.2.7
linter-clang, v3.3.0
linter-clojure, v1.1.2
linter-csslint, v1.2.0
linter-gcc, v0.5.11
linter-glsl, v1.0.6
linter-htmlhint, v0.2.2
linter-lua, v1.0.1
linter-luacheck, v1.1.4
linter-rust, v0.3.0
linter-tidy, v1.0.1
minimap, v4.19.0
nuclide-arcanist, v0.0.35
nuclide-blame, v0.0.35
nuclide-blame-provider-hg, v0.0.35
nuclide-blame-ui, v0.0.35
nuclide-buck-files, v0.0.35
nuclide-busy-signal, v0.0.35
nuclide-clang-atom, v0.0.35
nuclide-code-format, v0.0.35
nuclide-code-highlight, v0.0.35
nuclide-debugger-atom, v0.0.35
nuclide-debugger-hhvm, v0.0.35
nuclide-debugger-lldb, v0.0.35
nuclide-diagnostics-store, v0.0.35
nuclide-diagnostics-ui, v0.0.35
nuclide-diff-view, v0.0.35
nuclide-file-tree, v0.0.35
nuclide-file-watcher, v0.0.35
nuclide-find-references, v0.0.35
nuclide-flow, v0.0.35
nuclide-fuzzy-filename-provider, v0.0.35
nuclide-hack, v0.0.35
nuclide-hack-symbol-provider, v0.0.35
nuclide-health, v0.0.35
nuclide-hg-repository, v0.0.35
nuclide-home, v0.0.35
nuclide-installer, v0.0.35
nuclide-language-hack, v0.0.35
nuclide-objc, v0.0.35
nuclide-ocaml, v0.0.35
nuclide-open-filenames-provider, v0.0.35
nuclide-quick-open, v0.0.35
nuclide-recent-files-provider, v0.0.35
nuclide-recent-files-service, v0.0.35
nuclide-remote-projects, v0.0.35
nuclide-test-runner, v0.0.35
nuclide-toolbar, v0.0.35
nuclide-type-hint, v0.0.35
nuclide-url-hyperclick, v0.0.35
pdf-view, v0.39.0
project-manager, v2.7.1
tool-bar, v0.1.10
travis-ci-status, v0.18.0

# Dev
No dev packages
```

**Comment by urzds** [comment]
This happens on Atom 1.3.2 with Travis-CI-Status 0.18.0. I see the orange clock icon and the message "No build matrix fetched".

[Enter steps to reproduce below:]

1. Edit file in editor
2. Save file
3. Observe exception message

**Atom Version**: 1.3.2
**System**: Ubuntu 14.04.3
**Thrown From**: [travis-ci-status](https://github.com/tombell/travis-ci-status) package, v0.18.0


### Stack Trace

Uncaught TypeError: Cannot read property 'split' of null

```
At /usr/share/atom/resources/app.asar/src/pane.js:829

TypeError: Cannot read property 'split' of null
  at BuildStatusView.module.exports.BuildStatusView.update ($HOME/.atom/packages/travis-ci-status/lib/build-status-view.coffee:94:19)
  at $HOME/.atom/packages/travis-ci-status/lib/build-status-view.coffee:1:1
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
  at GitRepository.module.exports.GitRepository.getPathStatus (/usr/share/atom/resources/app.asar/src/git-repository.js:256:22)
  at /usr/share/atom/resources/app.asar/src/git-repository.js:326:26
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
  at TextBuffer.module.exports.TextBuffer.saveAs (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1060:27)
  at TextBuffer.module.exports.TextBuffer.save (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1030:19)
  at TextEditor.module.exports.TextEditor.save (/usr/share/atom/resources/app.asar/src/text-editor.js:588:26)
  at Pane.module.exports.Pane.saveItem (/usr/share/atom/resources/app.asar/src/pane.js:534:18)
  at Pane.module.exports.Pane.saveActiveItem (/usr/share/atom/resources/app.asar/src/pane.js:517:19)
  at Workspace.module.exports.Workspace.saveActivePaneItem (/usr/share/atom/resources/app.asar/src/workspace.js:633:35)
  at atom-workspace.commandRegistry.add.core:save (/usr/share/atom/resources/app.asar/src/register-default-commands.js:173:32)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
  at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:97:36)
  at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)

```

### Commands

```
     -7:10.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -7:02.8.0 command-palette:toggle (div.package-detail.panels-item)
     -7:00.4.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -7:00.4.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -6:53.4.0 command-palette:toggle (button.btn.icon.icon-trashcan.uninstall-button)
  5x -6:50.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -6:48.8.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -6:48.7.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -5:27.6.0 core:close (button.btn.icon.icon-trashcan.uninstall-button)
     -5:08.3.0 nuclide-health:open-pane (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -5:04.7.0 core:close (atom-pane.pane.active)
     -1:44.5.0 core:backspace (span.build-status.icon.icon-history.pending)
     -1:41.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:40.8.0 core:save (atom-text-editor.editor.is-focused)
     -1:38.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:38.1.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "linter",
      "tree-view"
    ]
  },
  "travis-ci-status": {}
}
```

### Installed Packages

```coffee
# User
Parinfer, v1.5.0
hyperclick, v0.0.35
language-cuda, v0.1.0
language-glsl, v2.0.1
language-hlsl, v1.2.0
language-hy, v0.1.0
language-latex, v0.6.1
language-lua, v0.9.4
language-opencl, v0.1.1
language-rust, v0.4.5
language-tmux, v0.4.0
latex, v0.28.2
latexer, v0.2.7
linter-clang, v3.3.0
linter-clojure, v1.1.2
linter-csslint, v1.2.0
linter-gcc, v0.5.11
linter-glsl, v1.0.6
linter-htmlhint, v0.2.2
linter-lua, v1.0.1
linter-luacheck, v1.1.4
linter-rust, v0.3.0
linter-tidy, v1.0.1
minimap, v4.19.0
nuclide-arcanist, v0.0.35
nuclide-blame, v0.0.35
nuclide-blame-provider-hg, v0.0.35
nuclide-blame-ui, v0.0.35
nuclide-buck-files, v0.0.35
nuclide-busy-signal, v0.0.35
nuclide-clang-atom, v0.0.35
nuclide-code-format, v0.0.35
nuclide-code-highlight, v0.0.35
nuclide-debugger-atom, v0.0.35
nuclide-debugger-hhvm, v0.0.35
nuclide-debugger-lldb, v0.0.35
nuclide-diagnostics-store, v0.0.35
nuclide-diagnostics-ui, v0.0.35
nuclide-diff-view, v0.0.35
nuclide-file-tree, v0.0.35
nuclide-file-watcher, v0.0.35
nuclide-find-references, v0.0.35
nuclide-flow, v0.0.35
nuclide-fuzzy-filename-provider, v0.0.35
nuclide-hack, v0.0.35
nuclide-hack-symbol-provider, v0.0.35
nuclide-health, v0.0.35
nuclide-hg-repository, v0.0.35
nuclide-home, v0.0.35
nuclide-installer, v0.0.35
nuclide-language-hack, v0.0.35
nuclide-objc, v0.0.35
nuclide-ocaml, v0.0.35
nuclide-open-filenames-provider, v0.0.35
nuclide-quick-open, v0.0.35
nuclide-recent-files-provider, v0.0.35
nuclide-recent-files-service, v0.0.35
nuclide-remote-projects, v0.0.35
nuclide-test-runner, v0.0.35
nuclide-toolbar, v0.0.35
nuclide-type-hint, v0.0.35
nuclide-url-hyperclick, v0.0.35
pdf-view, v0.39.0
project-manager, v2.7.1
tool-bar, v0.1.10
travis-ci-status, v0.18.0

# Dev
No dev packages
```
