### ISSUE TITLE
Uncaught TypeError: Cannot read property 'repos' of null

### ISSUE THREAD

**Issue by abinashmeher999** [tombell/travis-ci-status#66]
[Enter steps to reproduce below:]

1. Disabled travis-ci-status package

**Atom Version**: 1.0.0
**System**: Ubuntu 14.04.2
**Thrown From**: [travis-ci-status](https://github.com/tombell/travis-ci-status) package, v0.15.1

### Stack Trace

Uncaught TypeError: Cannot read property 'repos' of null

```
At /home/abinashmeher999/.atom/packages/travis-ci-status/lib/build-status-view.coffee:92

TypeError: Cannot read property 'repos' of null
  at /home/abinashmeher999/.atom/packages/travis-ci-status/lib/build-status-view.coffee:92:18
  at [object Object].<anonymous> (/home/abinashmeher999/.atom/packages/travis-ci-status/node_modules/travis-ci/lib/travis-ci.js:118:27)
  at /home/abinashmeher999/.atom/packages/travis-ci-status/node_modules/travis-ci/lib/travis-ci.js:51:21
  at Request._callback (/home/abinashmeher999/.atom/packages/travis-ci-status/node_modules/travis-ci/lib/travis-http.js:41:20)
  at self.callback (/home/abinashmeher999/.atom/packages/travis-ci-status/node_modules/travis-ci/node_modules/request/index.js:148:22)
  at emitOne (events.js:77:13)
  at Request.emit (events.js:166:7)
  at ClientRequest.self.clientErrorHandler (/home/abinashmeher999/.atom/packages/travis-ci-status/node_modules/travis-ci/node_modules/request/index.js:257:10)
  at emitOne (events.js:77:13)
  at ClientRequest.emit (events.js:166:7)
  at TLSSocket.socketErrorListener (_http_client.js:254:9)
  at emitOne (events.js:77:13)
  at TLSSocket.emit (events.js:166:7)
  at net.js:438:14
  at process._tickCallback (node.js:357:13)

```

### Commands

```
     -3:14.3.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -3:14.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -3:13.5.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -3:13.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -3:11 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -3:11 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -3:08.5.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -3:06.5.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -3:06.5.0 editor:newline (atom-text-editor.editor.is-focused)
  5x -3:02.1.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -3:00.2.0 core:move-down (atom-text-editor.editor.is-focused)
 30x -2:59.6.0 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "jonikorpi-atom-theme-ui",
      "jonikorpi-atom-solarized-syntax"
    ],
    "excludeVcsIgnoredPaths": false,
    "disabledPackages": [
      "markdown-preview",
      "atom-jshint",
      "atom-ternjs",
      "compass",
      "emmet",
      "irc",
      "language-latex",
      "latex",
      "git-plus",
      "color-picker",
      "git-control",
      "clipboard-plus",
      "editor-stats",
      "atom-color-highlight",
      "linter-js-yaml",
      "minimap-color-highlight",
      "pigments",
      "autocomplete-plus-python-jedi",
      "highlight-column",
      "tool-bar",
      "tool-bar-main",
      "terminal-status",
      "Sublime-Style-Column-Selection",
      "atom-fuzzy-grep",
      "auto-copyright",
      "autoclose-html",
      "docblockr",
      "gist-it",
      "key-peek",
      "linter-csslint",
      "linter-htmlhint",
      "linter-javac",
      "linter-jshint",
      "linter-pylint",
      "mathjax-wrapper",
      "minimap-bookmarks",
      "minimap-pigments",
      "pain-split",
      "set-syntax",
      "tabs-to-spaces",
      "travis-ci-status"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-clang, v0.8.6
autocomplete-paths, v1.0.2
autocomplete-ruby, v0.1.0
file-icons, v1.5.8
git-log, v0.4.1
hex, v0.6.2
highlight-line, v0.11.0
highlight-selected, v0.10.1
jonikorpi-atom-solarized-syntax, v0.2.4
jonikorpi-atom-theme-ui, v4.4.1
linter, v1.1.0
linter-cpplint, v0.1.4
linter-rubocop, v0.2.7
local-history, v3.2.3
markdown-preview-plus, v1.5.0
minimap, v4.10.2
minimap-autohide, v0.10.0
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.3
minimap-highlight-selected, v4.3.0
minimap-linter, v1.0.0
minimap-selection, v4.3.0
project-manager, v1.15.11
ruby-block, v0.3.4
save-session, v0.15.6
trailing-spaces, v0.3.2
underscorejs-snippets, v0.2.2

# Dev
No dev packages
```

**Comment by tombell** [comment]
Could not reproduce this using the latest Atom.

**Comment by Chaoste** [comment]
I am having the same Issue with the lastest Atom version on disabling the package:

Atom Version: 1.0.15
System: Windows 8.1
Thrown From: travis-ci-status package, v0.18.0

<pre>
Uncaught TypeError: Cannot read property 'repos' of null
/C:/Users/Thomas/.atom/packages/travis-ci-status/lib/build-status-view.coffee:120
Hide Stack Trace
TypeError: Cannot read property 'repos' of null
  at C:\Users\Thomas\.atom\packages\travis-ci-status\lib\build-status-view.coffee:97:18
  at [object Object].<anonymous> (C:\Users\Thomas\.atom\packages\travis-ci-status\node_modules\travis-ci\lib\travis-ci.js:109:16)
  at Request._callback (C:\Users\Thomas\.atom\packages\travis-ci-status\node_modules\travis-ci\lib\travis-http.js:51:13)
  at Request.self.callback (C:\Users\Thomas\.atom\packages\travis-ci-status\node_modules\travis-ci\node_modules\request\index.js:148:22)
  at emitTwo (events.js:87:13)
  at Request.emit (events.js:172:7)
  at Request.<anonymous> (C:\Users\Thomas\.atom\packages\travis-ci-status\node_modules\travis-ci\node_modules\request\index.js:886:14)
  at emitOne (events.js:82:20)
  at Request.emit (events.js:169:7)
  at IncomingMessage.<anonymous> (C:\Users\Thomas\.atom\packages\travis-ci-status\node_modules\travis-ci\node_modules\request\index.js:837:12)
  at emitNone (events.js:72:20)
  at IncomingMessage.emit (events.js:166:7)
  at endReadableNT (_stream_readable.js:889:12)
  at doNTCallback2 (node.js:438:9)
  at process._tickCallback (node.js:352:17)
</pre>

**Comment by abinashmeher999** [comment]
@tombell Seems like the bug has reappeared.

**Comment by tombell** [comment]
If someone wishes to hunt it down and fix it I'll accept a PR, I don't have the personal time to investigate.

**Comment by tombell** [comment]
Cannot reproduce this using v1.3.3.

**Comment by AutomatedTester** [comment]
I just got this after upgrading to Atom 1.4 and upgrading to 1.0.0. Not sure if there is something related to everything updating at once?
