### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getConfigValue' of null

### ISSUE THREAD

**Issue by rahul-rkt** [tombell/travis-ci-status#67]
Updated Atom to 1.0.2 and this started popping up!

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.3
**Thrown From**: [travis-ci-status](https://github.com/tombell/travis-ci-status) package, v0.15.1

### Stack Trace

Uncaught TypeError: Cannot read property 'getConfigValue' of null

```
At /Users/rahulthakur/.atom/packages/travis-ci-status/lib/build-status-view.coffee:73

TypeError: Cannot read property 'getConfigValue' of null
    at /Users/rahulthakur/.atom/packages/travis-ci-status/lib/build-status-view.coffee:95:41
    at Array.filter (native)
    at BuildStatusView.module.exports.BuildStatusView.subscribeToRepo (/Users/rahulthakur/.atom/packages/travis-ci-status/lib/build-status-view.coffee:94:20)
    at BuildStatusView.subscribeToRepo (/Users/rahulthakur/.atom/packages/travis-ci-status/lib/build-status-view.coffee:3:61)
    at BuildStatusView.module.exports.BuildStatusView.initialize (/Users/rahulthakur/.atom/packages/travis-ci-status/lib/build-status-view.coffee:49:19)
    at BuildStatusView.View (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
    at new BuildStatusView (/Users/rahulthakur/.atom/packages/travis-ci-status/lib/build-status-view.coffee:18:52)
    at /Users/rahulthakur/.atom/packages/travis-ci-status/lib/travis-ci-status.coffee:114:42
    at Object.module.exports.init (/Users/rahulthakur/.atom/packages/travis-ci-status/lib/travis-ci-status.coffee:119:9)
    at /Users/rahulthakur/.atom/packages/travis-ci-status/lib/travis-ci-status.coffee:38:38
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "base16-ocean-dark-syntax-theme"
    ],
    "ignoredNames": [
      ".git",
      ".DS_Store",
      ".vagrant",
      "_site",
      ".sass-cache",
      ".idea .brackets.json"
    ],
    "disabledPackages": [
      "markdown-preview",
      "minimap",
      "minimap-highlight-selected"
    ]
  },
  "travis-ci-status": {}
}
```

### Installed Packages

```coffee
# User
atom-html-preview, v0.1.9
atom-jshint, v2.0.0
atom-minify, v0.1.7
auto-update-packages, v1.0.0
autocomplete-php, v0.3.6
base16-ocean-dark-syntax-theme, v0.1.5
color-picker, v2.0.9
emmet, v2.3.12
file-icons, v1.5.8
highlight-selected, v0.10.1
language-jade, v0.5.1
language-liquid, v0.2.0
markdown-preview-plus, v1.5.0
package-sync, v0.2.0
php-debug, v0.1.2
project-manager, v1.15.11
save-session, v0.15.6
svg-preview, v0.6.0
tabs-to-spaces, v0.11.0
terminal-status, v1.6.8
trailing-spaces, v0.3.2
travis-ci-status, v0.15.1

# Dev
No dev packages
```

**Comment by tombell** [comment]
Could not reproduce this using the latest Atom and travis-ci-status.

**Comment by Chaoste** [comment]
I have the same problem.

Atom Version: 1.0.15
System: Windows 8.1
Thrown From: travis-ci-status package, v0.18.0

The error appeared after the first restart of Atom. Before the restart it kind of worked: It only called the wrong repository on travis-ci.org, but the opened project was on magnum.travis-ci.com. Can anyone tell me what the difference is? Also it called the travis url 6 times - weird bug ^^

<pre>
Uncaught TypeError: Cannot read property 'getConfigValue' of null
/C:/Users/Thomas/.atom/packages/travis-ci-status/lib/travis-ci-status.coffee:77
Hide Stack Trace
TypeError: Cannot read property 'getConfigValue' of null
  at Object.module.exports.getNameWithOwner (C:\Users\Thomas\.atom\packages\travis-ci-status\lib\travis-ci-status.coffee:78:16)
  at Object.module.exports.openOnTravis (C:\Users\Thomas\.atom\packages\travis-ci-status\lib\travis-ci-status.coffee:124:12)
  at atom-workspace.<anonymous> (C:\Users\Thomas\.atom\packages\travis-ci-status\lib\travis-ci-status.coffee:109:8)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Thomas\AppData\Local\atom\app-1.0.15\resources\app.asar\src\command-registry.js:245:29)
  at C:\Users\Thomas\AppData\Local\atom\app-1.0.15\resources\app.asar\src\command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (C:\Users\Thomas\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\command-palette\lib\command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (C:\Users\Thomas\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (C:\Users\Thomas\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Thomas\AppData\Local\atom\app-1.0.15\resources\app.asar\src\command-registry.js:245:29)
  at C:\Users\Thomas\AppData\Local\atom\app-1.0.15\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\Thomas\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\Thomas\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\Thomas\AppData\Local\atom\app-1.0.15\resources\app.asar\src\window-event-handler.js:184:20)
</pre>
