### ISSUE TITLE
Uncaught AssertionError: false == true

### ISSUE THREAD

**Issue by laughedelic** [tombell/travis-ci-status#68]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.5
**System**: Mac OS X 10.10.5
**Thrown From**: [travis-ci-status](https://github.com/tombell/travis-ci-status) package, v0.16.0

### Stack Trace

Uncaught AssertionError: false == true

```
At assert.js:87

AssertionError: false == true
  at [object Object].TravisClient._authenticateAccessToken (/Users/laughedelic/.atom/packages/travis-ci-status/node_modules/travis-ci/lib/travis-ci.js:102:5)
  at [object Object].<anonymous> (/Users/laughedelic/.atom/packages/travis-ci-status/node_modules/travis-ci/lib/travis-ci.js:120:14)
  at /Users/laughedelic/.atom/packages/travis-ci-status/node_modules/travis-ci/lib/travis-ci.js:51:21
  at Request._callback (/Users/laughedelic/.atom/packages/travis-ci-status/node_modules/travis-ci/lib/travis-http.js:51:13)
  at Request.self.callback (/Users/laughedelic/.atom/packages/travis-ci-status/node_modules/travis-ci/node_modules/request/index.js:148:22)
  at emitTwo (events.js:87:13)
  at Request.emit (events.js:169:7)
  at Request.<anonymous> (/Users/laughedelic/.atom/packages/travis-ci-status/node_modules/travis-ci/node_modules/request/index.js:886:14)
  at emitOne (events.js:82:20)
  at Request.emit (events.js:166:7)
  at IncomingMessage.<anonymous> (/Users/laughedelic/.atom/packages/travis-ci-status/node_modules/travis-ci/node_modules/request/index.js:837:12)
  at emitNone (events.js:72:20)
  at IncomingMessage.emit (events.js:163:7)
  at _stream_readable.js:891:16
  at process._tickCallback (node.js:357:13)

```

### Commands

```
     -0:05.6.0 window:toggle-dev-tools (atom-text-editor.editor.is-focused.vim-mode.normal-mode)
```

### Config

```json
{
  "core": {
    "projectHome": "~/dev",
    "audioBeep": false,
    "disabledPackages": [
      "keybinding-resolver",
      "language-objective-c",
      "distraction-free-mode",
      "language-gfm",
      "autocomplete",
      "markdown-writer",
      "markdown-lists",
      "markmon-preview",
      "markdown-preview",
      "block-cursor",
      "remember-session",
      "gitter",
      "Clean",
      "texlicious",
      "autoflow-diffable",
      "tree-view-finder",
      "mechanical-keyboard",
      "git-control",
      "git-projects",
      "autocomplete-css",
      "git-tab-status",
      "wakatime",
      "minimap-git-diff",
      "autocomplete-atom-api",
      "language-clojure",
      "language-git",
      "language-html",
      "language-javascript",
      "language-less",
      "language-ruby",
      "language-c",
      "language-csharp",
      "language-go",
      "language-make",
      "language-mustache",
      "language-perl",
      "language-php",
      "language-python",
      "language-ruby-on-rails",
      "language-sass",
      "language-sql",
      "language-toml",
      "language-xml",
      "task-list",
      "academic",
      "autocomplete-haskell",
      "ide-haskell",
      "markdown-preview-katex",
      "markdown-preview-pandoc",
      "atom-markdown-katex",
      "scala-worksheet",
      "scala-worksheet",
      "scala-worksheet",
      "markdown-scroll-sync",
      "project-manager",
      "license-plus",
      "key-peek",
      "last-cursor-position",
      "language-idris",
      "vim-mode-clipboard-plus",
      "clipboard-plus",
      "autocomplete-snippets",
      "symbols-tree-view",
      "autocomplete-html",
      "move-status-items",
      "atom-notifier",
      "autocomplete-paths",
      "semanticolor",
      "svg-preview",
      "symbols-view",
      "todo-show",
      "Termrk",
      "autocomplete-bibtex",
      "autocomplete-ctags",
      "tree-view-git-branch",
      "atom-itunes",
      "linter-scspell",
      "atom-pair",
      "build",
      "linter",
      "haskell-ghc-mod"
    ],
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  },
  "travis-ci-status": {
    "personalAccessToken": "107825e534e7e6ed9afefe40c3aca98fe6b08810"
  }
}
```

### Installed Packages

```coffee
# User
Ensime, v0.17.0
atom-ctags, v4.1.4
atom-material-syntax, v0.2.1
atom-material-ui, v0.5.13
autocomplete-emojis, v2.2.2
bottom-dock, v0.2.0
branch-status, v0.8.1
cursor-history, v0.4.17
file-icons, v1.6.2
highlight-selected, v0.10.1
language-elm, v0.5.0
language-haskell, v1.3.0
language-latex, v0.6.1
language-pfm, v0.81.0
language-restructuredtext, v0.7.0
language-scala, v1.1.3
latex-completions, v0.3.0
line-diff-details, v1.1.2
linter-scalac, v1.0.2
markdown-mindmap, v0.2.1
markdown-preview-plus, v1.6.0
markdown-table-formatter, v2.5.2
mathjax-wrapper, v0.1.0
minimap, v4.12.2
package-manager-commands, v2.0.3
package-switch, v0.3.0
pdf-view, v0.23.0
preview-inline, v0.4.1
set-syntax, v0.3.0
todo-manager, v0.1.6
travis-ci-status, v0.16.0
vim-mode, v0.57.0

# Dev
No dev packages
```

**Comment by tombell** [comment]
This is an error with the access token in the travis-ci lib. Make sure you've followed the instructions for setting the token https://github.com/tombell/travis-ci-status#travis-pro
